### PR TITLE
BRO

### PR DESCRIPTION
**Pull request by Quartinal**
pls merge; i don't have admin access this organization...

### CODE REVIEW

**Comment by qwertychomp** [comment]
alr il go merge, sorry about preston removing you. he was probably annoyed about how you messed up the analytics with your prettier

**Comment by PrestonT500** [comment]
No it was because he was not doing any work

**Comment by PrestonT500** [comment]
the prettier commit didnt count

**Comment by Quartinal** [comment]
> No it was because he was not doing any work

I did commit changes, someone just deleted the link to Comet.

**Comment by qwertychomp** [comment]
with all due respect putting an advertisement to your own project doesnt really count as work either

**Comment by Quartinal** [comment]
> with all due respect putting an advertisement to your own project doesnt really count as work either

that's fair. plus, i have other stuff i'm working on like comet, and i'm spending a lot of time on those things.

**Pull request merged**
